<?php
/**
 * DollarSignAgeGatedDateOfBirthEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klaviyo API
 *
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KlaviyoAPI\Model;
use \KlaviyoAPI\ObjectSerializer;

/**
 * DollarSignAgeGatedDateOfBirthEnum Class Doc Comment
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DollarSignAgeGatedDateOfBirthEnum
{
    /**
     * Possible values of this enum
     */
    public const _AGE_GATED_DATE_OF_BIRTH = '$age_gated_date_of_birth';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_AGE_GATED_DATE_OF_BIRTH
        ];
    }
}


