<?php
/**
 * ReviewProperties
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klaviyo API
 *
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KlaviyoAPI\Model;

use \ArrayAccess;
use \KlaviyoAPI\ObjectSerializer;

/**
 * ReviewProperties Class Doc Comment
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReviewProperties implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReviewProperties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'display_device' => 'string[]',
        'author' => 'string',
        'content' => 'string',
        'rating' => 'int',
        'verified' => 'bool',
        'review_id' => 'int',
        'show_rating' => 'bool',
        'show_author' => 'bool',
        'show_verified' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'display_device' => null,
        'author' => null,
        'content' => null,
        'rating' => null,
        'verified' => null,
        'review_id' => null,
        'show_rating' => null,
        'show_author' => null,
        'show_verified' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'display_device' => false,
        'author' => true,
        'content' => true,
        'rating' => false,
        'verified' => false,
        'review_id' => true,
        'show_rating' => false,
        'show_author' => false,
        'show_verified' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'display_device' => 'display_device',
        'author' => 'author',
        'content' => 'content',
        'rating' => 'rating',
        'verified' => 'verified',
        'review_id' => 'review_id',
        'show_rating' => 'show_rating',
        'show_author' => 'show_author',
        'show_verified' => 'show_verified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'display_device' => 'setDisplayDevice',
        'author' => 'setAuthor',
        'content' => 'setContent',
        'rating' => 'setRating',
        'verified' => 'setVerified',
        'review_id' => 'setReviewId',
        'show_rating' => 'setShowRating',
        'show_author' => 'setShowAuthor',
        'show_verified' => 'setShowVerified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'display_device' => 'getDisplayDevice',
        'author' => 'getAuthor',
        'content' => 'getContent',
        'rating' => 'getRating',
        'verified' => 'getVerified',
        'review_id' => 'getReviewId',
        'show_rating' => 'getShowRating',
        'show_author' => 'getShowAuthor',
        'show_verified' => 'getShowVerified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DISPLAY_DEVICE_BOTH = 'both';
    public const DISPLAY_DEVICE_DESKTOP = 'desktop';
    public const DISPLAY_DEVICE_MOBILE = 'mobile';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDisplayDeviceAllowableValues()
    {
        return [
            self::DISPLAY_DEVICE_BOTH,
            self::DISPLAY_DEVICE_DESKTOP,
            self::DISPLAY_DEVICE_MOBILE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('display_device', $data ?? [], null);
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('rating', $data ?? [], 5);
        $this->setIfExists('verified', $data ?? [], false);
        $this->setIfExists('review_id', $data ?? [], null);
        $this->setIfExists('show_rating', $data ?? [], true);
        $this->setIfExists('show_author', $data ?? [], true);
        $this->setIfExists('show_verified', $data ?? [], true);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets display_device
     *
     * @return string[]|null
     */
    public function getDisplayDevice()
    {
        return $this->container['display_device'];
    }

    /**
     * Sets display_device
     *
     * @param string[]|null $display_device display_device
     *
     * @return self
     */
    public function setDisplayDevice($display_device)
    {
        if (is_null($display_device)) {
            throw new \InvalidArgumentException('non-nullable display_device cannot be null');
        }
        $allowedValues = $this->getDisplayDeviceAllowableValues();
        if (array_diff($display_device, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'display_device', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['display_device'] = $display_device;

        return $this;
    }

    /**
     * Gets author
     *
     * @return string|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string|null $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            array_push($this->openAPINullablesSetToNull, 'author');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('author', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            array_push($this->openAPINullablesSetToNull, 'content');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('content', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets rating
     *
     * @return int|null
     */
    public function getRating()
    {
        return $this->container['rating'];
    }

    /**
     * Sets rating
     *
     * @param int|null $rating rating
     *
     * @return self
     */
    public function setRating($rating)
    {
        if (is_null($rating)) {
            throw new \InvalidArgumentException('non-nullable rating cannot be null');
        }
        $this->container['rating'] = $rating;

        return $this;
    }

    /**
     * Gets verified
     *
     * @return bool|null
     */
    public function getVerified()
    {
        return $this->container['verified'];
    }

    /**
     * Sets verified
     *
     * @param bool|null $verified verified
     *
     * @return self
     */
    public function setVerified($verified)
    {
        if (is_null($verified)) {
            throw new \InvalidArgumentException('non-nullable verified cannot be null');
        }
        $this->container['verified'] = $verified;

        return $this;
    }

    /**
     * Gets review_id
     *
     * @return int|null
     */
    public function getReviewId()
    {
        return $this->container['review_id'];
    }

    /**
     * Sets review_id
     *
     * @param int|null $review_id review_id
     *
     * @return self
     */
    public function setReviewId($review_id)
    {
        if (is_null($review_id)) {
            array_push($this->openAPINullablesSetToNull, 'review_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('review_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['review_id'] = $review_id;

        return $this;
    }

    /**
     * Gets show_rating
     *
     * @return bool|null
     */
    public function getShowRating()
    {
        return $this->container['show_rating'];
    }

    /**
     * Sets show_rating
     *
     * @param bool|null $show_rating show_rating
     *
     * @return self
     */
    public function setShowRating($show_rating)
    {
        if (is_null($show_rating)) {
            throw new \InvalidArgumentException('non-nullable show_rating cannot be null');
        }
        $this->container['show_rating'] = $show_rating;

        return $this;
    }

    /**
     * Gets show_author
     *
     * @return bool|null
     */
    public function getShowAuthor()
    {
        return $this->container['show_author'];
    }

    /**
     * Sets show_author
     *
     * @param bool|null $show_author show_author
     *
     * @return self
     */
    public function setShowAuthor($show_author)
    {
        if (is_null($show_author)) {
            throw new \InvalidArgumentException('non-nullable show_author cannot be null');
        }
        $this->container['show_author'] = $show_author;

        return $this;
    }

    /**
     * Gets show_verified
     *
     * @return bool|null
     */
    public function getShowVerified()
    {
        return $this->container['show_verified'];
    }

    /**
     * Sets show_verified
     *
     * @param bool|null $show_verified show_verified
     *
     * @return self
     */
    public function setShowVerified($show_verified)
    {
        if (is_null($show_verified)) {
            throw new \InvalidArgumentException('non-nullable show_verified cannot be null');
        }
        $this->container['show_verified'] = $show_verified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


