<?php
/**
 * RichTextStyle
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klaviyo API
 *
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KlaviyoAPI\Model;

use \ArrayAccess;
use \KlaviyoAPI\ObjectSerializer;

/**
 * RichTextStyle Class Doc Comment
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RichTextStyle implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RichTextStyle';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'font_family' => '\KlaviyoAPI\Model\TextStyleFontFamily',
        'font_size' => 'int',
        'font_weight' => 'int',
        'text_color' => 'string',
        'line_spacing' => 'float',
        'character_spacing' => 'int',
        'alignment' => 'string',
        'margin' => '\KlaviyoAPI\Model\RichTextMargin'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'font_family' => null,
        'font_size' => null,
        'font_weight' => null,
        'text_color' => null,
        'line_spacing' => null,
        'character_spacing' => null,
        'alignment' => null,
        'margin' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'font_family' => false,
        'font_size' => false,
        'font_weight' => true,
        'text_color' => false,
        'line_spacing' => false,
        'character_spacing' => true,
        'alignment' => false,
        'margin' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'font_family' => 'font_family',
        'font_size' => 'font_size',
        'font_weight' => 'font_weight',
        'text_color' => 'text_color',
        'line_spacing' => 'line_spacing',
        'character_spacing' => 'character_spacing',
        'alignment' => 'alignment',
        'margin' => 'margin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'font_family' => 'setFontFamily',
        'font_size' => 'setFontSize',
        'font_weight' => 'setFontWeight',
        'text_color' => 'setTextColor',
        'line_spacing' => 'setLineSpacing',
        'character_spacing' => 'setCharacterSpacing',
        'alignment' => 'setAlignment',
        'margin' => 'setMargin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'font_family' => 'getFontFamily',
        'font_size' => 'getFontSize',
        'font_weight' => 'getFontWeight',
        'text_color' => 'getTextColor',
        'line_spacing' => 'getLineSpacing',
        'character_spacing' => 'getCharacterSpacing',
        'alignment' => 'getAlignment',
        'margin' => 'getMargin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FONT_WEIGHT_NUMBER_100 = 100;
    public const FONT_WEIGHT_NUMBER_200 = 200;
    public const FONT_WEIGHT_NUMBER_300 = 300;
    public const FONT_WEIGHT_NUMBER_400 = 400;
    public const FONT_WEIGHT_NUMBER_500 = 500;
    public const FONT_WEIGHT_NUMBER_600 = 600;
    public const FONT_WEIGHT_NUMBER_700 = 700;
    public const FONT_WEIGHT_NUMBER_800 = 800;
    public const FONT_WEIGHT_NUMBER_900 = 900;
    public const ALIGNMENT_CENTER = 'center';
    public const ALIGNMENT_LEFT = 'left';
    public const ALIGNMENT_RIGHT = 'right';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFontWeightAllowableValues()
    {
        return [
            self::FONT_WEIGHT_NUMBER_100,
            self::FONT_WEIGHT_NUMBER_200,
            self::FONT_WEIGHT_NUMBER_300,
            self::FONT_WEIGHT_NUMBER_400,
            self::FONT_WEIGHT_NUMBER_500,
            self::FONT_WEIGHT_NUMBER_600,
            self::FONT_WEIGHT_NUMBER_700,
            self::FONT_WEIGHT_NUMBER_800,
            self::FONT_WEIGHT_NUMBER_900,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAlignmentAllowableValues()
    {
        return [
            self::ALIGNMENT_CENTER,
            self::ALIGNMENT_LEFT,
            self::ALIGNMENT_RIGHT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('font_family', $data ?? [], null);
        $this->setIfExists('font_size', $data ?? [], 16);
        $this->setIfExists('font_weight', $data ?? [], self::FONT_WEIGHT_NUMBER_400);
        $this->setIfExists('text_color', $data ?? [], '#000000');
        $this->setIfExists('line_spacing', $data ?? [], 1);
        $this->setIfExists('character_spacing', $data ?? [], 0);
        $this->setIfExists('alignment', $data ?? [], 'left');
        $this->setIfExists('margin', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFontWeightAllowableValues();
        if (!is_null($this->container['font_weight']) && !in_array($this->container['font_weight'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'font_weight', must be one of '%s'",
                $this->container['font_weight'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAlignmentAllowableValues();
        if (!is_null($this->container['alignment']) && !in_array($this->container['alignment'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'alignment', must be one of '%s'",
                $this->container['alignment'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets font_family
     *
     * @return \KlaviyoAPI\Model\TextStyleFontFamily|null
     */
    public function getFontFamily()
    {
        return $this->container['font_family'];
    }

    /**
     * Sets font_family
     *
     * @param \KlaviyoAPI\Model\TextStyleFontFamily|null $font_family font_family
     *
     * @return self
     */
    public function setFontFamily($font_family)
    {
        if (is_null($font_family)) {
            throw new \InvalidArgumentException('non-nullable font_family cannot be null');
        }
        $this->container['font_family'] = $font_family;

        return $this;
    }

    /**
     * Gets font_size
     *
     * @return int|null
     */
    public function getFontSize()
    {
        return $this->container['font_size'];
    }

    /**
     * Sets font_size
     *
     * @param int|null $font_size font_size
     *
     * @return self
     */
    public function setFontSize($font_size)
    {
        if (is_null($font_size)) {
            throw new \InvalidArgumentException('non-nullable font_size cannot be null');
        }
        $this->container['font_size'] = $font_size;

        return $this;
    }

    /**
     * Gets font_weight
     *
     * @return int|null
     */
    public function getFontWeight()
    {
        return $this->container['font_weight'];
    }

    /**
     * Sets font_weight
     *
     * @param int|null $font_weight Font weight enumeration.
     *
     * @return self
     */
    public function setFontWeight($font_weight)
    {
        if (is_null($font_weight)) {
            array_push($this->openAPINullablesSetToNull, 'font_weight');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font_weight', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getFontWeightAllowableValues();
        if (!is_null($font_weight) && !in_array($font_weight, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'font_weight', must be one of '%s'",
                    $font_weight,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['font_weight'] = $font_weight;

        return $this;
    }

    /**
     * Gets text_color
     *
     * @return string|null
     */
    public function getTextColor()
    {
        return $this->container['text_color'];
    }

    /**
     * Sets text_color
     *
     * @param string|null $text_color text_color
     *
     * @return self
     */
    public function setTextColor($text_color)
    {
        if (is_null($text_color)) {
            throw new \InvalidArgumentException('non-nullable text_color cannot be null');
        }
        $this->container['text_color'] = $text_color;

        return $this;
    }

    /**
     * Gets line_spacing
     *
     * @return float|null
     */
    public function getLineSpacing()
    {
        return $this->container['line_spacing'];
    }

    /**
     * Sets line_spacing
     *
     * @param float|null $line_spacing line_spacing
     *
     * @return self
     */
    public function setLineSpacing($line_spacing)
    {
        if (is_null($line_spacing)) {
            throw new \InvalidArgumentException('non-nullable line_spacing cannot be null');
        }
        $this->container['line_spacing'] = $line_spacing;

        return $this;
    }

    /**
     * Gets character_spacing
     *
     * @return int|null
     */
    public function getCharacterSpacing()
    {
        return $this->container['character_spacing'];
    }

    /**
     * Sets character_spacing
     *
     * @param int|null $character_spacing character_spacing
     *
     * @return self
     */
    public function setCharacterSpacing($character_spacing)
    {
        if (is_null($character_spacing)) {
            array_push($this->openAPINullablesSetToNull, 'character_spacing');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('character_spacing', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['character_spacing'] = $character_spacing;

        return $this;
    }

    /**
     * Gets alignment
     *
     * @return string|null
     */
    public function getAlignment()
    {
        return $this->container['alignment'];
    }

    /**
     * Sets alignment
     *
     * @param string|null $alignment Horizontal alignment enumeration.
     *
     * @return self
     */
    public function setAlignment($alignment)
    {
        if (is_null($alignment)) {
            throw new \InvalidArgumentException('non-nullable alignment cannot be null');
        }
        $allowedValues = $this->getAlignmentAllowableValues();
        if (!in_array($alignment, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'alignment', must be one of '%s'",
                    $alignment,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['alignment'] = $alignment;

        return $this;
    }

    /**
     * Gets margin
     *
     * @return \KlaviyoAPI\Model\RichTextMargin|null
     */
    public function getMargin()
    {
        return $this->container['margin'];
    }

    /**
     * Sets margin
     *
     * @param \KlaviyoAPI\Model\RichTextMargin|null $margin margin
     *
     * @return self
     */
    public function setMargin($margin)
    {
        if (is_null($margin)) {
            throw new \InvalidArgumentException('non-nullable margin cannot be null');
        }
        $this->container['margin'] = $margin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


