<?php
/**
 * TableBlockStyles
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Klaviyo API
 *
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * Contact: developers@klaviyo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace KlaviyoAPI\Model;

use \ArrayAccess;
use \KlaviyoAPI\ObjectSerializer;

/**
 * TableBlockStyles Class Doc Comment
 *
 * @category Class
 * @package  KlaviyoAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TableBlockStyles implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TableBlockStyles';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'block_background_color' => 'string',
        'block_border_color' => 'string',
        'block_border_style' => 'string',
        'block_border_width' => 'int',
        'block_padding_bottom' => 'int',
        'block_padding_left' => 'int',
        'block_padding_right' => 'int',
        'block_padding_top' => 'int',
        'cell_horizontal_border_color' => 'string',
        'cell_horizontal_border_style' => 'string',
        'cell_horizontal_border_width' => 'int',
        'cell_padding_bottom' => 'int',
        'cell_padding_left' => 'int',
        'cell_padding_right' => 'int',
        'cell_padding_top' => 'int',
        'cell_vertical_align' => 'string',
        'cell_vertical_border_color' => 'string',
        'cell_vertical_border_style' => 'string',
        'cell_vertical_border_width' => 'int',
        'header_background_color' => 'string',
        'header_font_color' => 'string',
        'header_font_family' => 'string',
        'header_font_size' => 'int',
        'header_font_style' => 'string',
        'header_font_weight' => 'string',
        'header_letter_spacing' => 'int',
        'header_line_height' => 'float',
        'header_padding_bottom' => 'int',
        'header_padding_left' => 'int',
        'header_padding_right' => 'int',
        'header_padding_top' => 'int',
        'header_text_decoration' => 'string',
        'table_background_color' => 'string',
        'table_font_color' => 'string',
        'table_font_family' => 'string',
        'table_font_size' => 'int',
        'table_text_align' => 'string',
        'use_legacy_mobile_padding' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'block_background_color' => null,
        'block_border_color' => null,
        'block_border_style' => null,
        'block_border_width' => null,
        'block_padding_bottom' => null,
        'block_padding_left' => null,
        'block_padding_right' => null,
        'block_padding_top' => null,
        'cell_horizontal_border_color' => null,
        'cell_horizontal_border_style' => null,
        'cell_horizontal_border_width' => null,
        'cell_padding_bottom' => null,
        'cell_padding_left' => null,
        'cell_padding_right' => null,
        'cell_padding_top' => null,
        'cell_vertical_align' => null,
        'cell_vertical_border_color' => null,
        'cell_vertical_border_style' => null,
        'cell_vertical_border_width' => null,
        'header_background_color' => null,
        'header_font_color' => null,
        'header_font_family' => null,
        'header_font_size' => null,
        'header_font_style' => null,
        'header_font_weight' => null,
        'header_letter_spacing' => null,
        'header_line_height' => null,
        'header_padding_bottom' => null,
        'header_padding_left' => null,
        'header_padding_right' => null,
        'header_padding_top' => null,
        'header_text_decoration' => null,
        'table_background_color' => null,
        'table_font_color' => null,
        'table_font_family' => null,
        'table_font_size' => null,
        'table_text_align' => null,
        'use_legacy_mobile_padding' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'block_background_color' => true,
        'block_border_color' => true,
        'block_border_style' => true,
        'block_border_width' => true,
        'block_padding_bottom' => true,
        'block_padding_left' => true,
        'block_padding_right' => true,
        'block_padding_top' => true,
        'cell_horizontal_border_color' => true,
        'cell_horizontal_border_style' => true,
        'cell_horizontal_border_width' => true,
        'cell_padding_bottom' => true,
        'cell_padding_left' => true,
        'cell_padding_right' => true,
        'cell_padding_top' => true,
        'cell_vertical_align' => true,
        'cell_vertical_border_color' => true,
        'cell_vertical_border_style' => true,
        'cell_vertical_border_width' => true,
        'header_background_color' => true,
        'header_font_color' => true,
        'header_font_family' => true,
        'header_font_size' => true,
        'header_font_style' => true,
        'header_font_weight' => true,
        'header_letter_spacing' => true,
        'header_line_height' => true,
        'header_padding_bottom' => true,
        'header_padding_left' => true,
        'header_padding_right' => true,
        'header_padding_top' => true,
        'header_text_decoration' => true,
        'table_background_color' => true,
        'table_font_color' => true,
        'table_font_family' => true,
        'table_font_size' => true,
        'table_text_align' => true,
        'use_legacy_mobile_padding' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'block_background_color' => 'block_background_color',
        'block_border_color' => 'block_border_color',
        'block_border_style' => 'block_border_style',
        'block_border_width' => 'block_border_width',
        'block_padding_bottom' => 'block_padding_bottom',
        'block_padding_left' => 'block_padding_left',
        'block_padding_right' => 'block_padding_right',
        'block_padding_top' => 'block_padding_top',
        'cell_horizontal_border_color' => 'cell_horizontal_border_color',
        'cell_horizontal_border_style' => 'cell_horizontal_border_style',
        'cell_horizontal_border_width' => 'cell_horizontal_border_width',
        'cell_padding_bottom' => 'cell_padding_bottom',
        'cell_padding_left' => 'cell_padding_left',
        'cell_padding_right' => 'cell_padding_right',
        'cell_padding_top' => 'cell_padding_top',
        'cell_vertical_align' => 'cell_vertical_align',
        'cell_vertical_border_color' => 'cell_vertical_border_color',
        'cell_vertical_border_style' => 'cell_vertical_border_style',
        'cell_vertical_border_width' => 'cell_vertical_border_width',
        'header_background_color' => 'header_background_color',
        'header_font_color' => 'header_font_color',
        'header_font_family' => 'header_font_family',
        'header_font_size' => 'header_font_size',
        'header_font_style' => 'header_font_style',
        'header_font_weight' => 'header_font_weight',
        'header_letter_spacing' => 'header_letter_spacing',
        'header_line_height' => 'header_line_height',
        'header_padding_bottom' => 'header_padding_bottom',
        'header_padding_left' => 'header_padding_left',
        'header_padding_right' => 'header_padding_right',
        'header_padding_top' => 'header_padding_top',
        'header_text_decoration' => 'header_text_decoration',
        'table_background_color' => 'table_background_color',
        'table_font_color' => 'table_font_color',
        'table_font_family' => 'table_font_family',
        'table_font_size' => 'table_font_size',
        'table_text_align' => 'table_text_align',
        'use_legacy_mobile_padding' => 'use_legacy_mobile_padding'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'block_background_color' => 'setBlockBackgroundColor',
        'block_border_color' => 'setBlockBorderColor',
        'block_border_style' => 'setBlockBorderStyle',
        'block_border_width' => 'setBlockBorderWidth',
        'block_padding_bottom' => 'setBlockPaddingBottom',
        'block_padding_left' => 'setBlockPaddingLeft',
        'block_padding_right' => 'setBlockPaddingRight',
        'block_padding_top' => 'setBlockPaddingTop',
        'cell_horizontal_border_color' => 'setCellHorizontalBorderColor',
        'cell_horizontal_border_style' => 'setCellHorizontalBorderStyle',
        'cell_horizontal_border_width' => 'setCellHorizontalBorderWidth',
        'cell_padding_bottom' => 'setCellPaddingBottom',
        'cell_padding_left' => 'setCellPaddingLeft',
        'cell_padding_right' => 'setCellPaddingRight',
        'cell_padding_top' => 'setCellPaddingTop',
        'cell_vertical_align' => 'setCellVerticalAlign',
        'cell_vertical_border_color' => 'setCellVerticalBorderColor',
        'cell_vertical_border_style' => 'setCellVerticalBorderStyle',
        'cell_vertical_border_width' => 'setCellVerticalBorderWidth',
        'header_background_color' => 'setHeaderBackgroundColor',
        'header_font_color' => 'setHeaderFontColor',
        'header_font_family' => 'setHeaderFontFamily',
        'header_font_size' => 'setHeaderFontSize',
        'header_font_style' => 'setHeaderFontStyle',
        'header_font_weight' => 'setHeaderFontWeight',
        'header_letter_spacing' => 'setHeaderLetterSpacing',
        'header_line_height' => 'setHeaderLineHeight',
        'header_padding_bottom' => 'setHeaderPaddingBottom',
        'header_padding_left' => 'setHeaderPaddingLeft',
        'header_padding_right' => 'setHeaderPaddingRight',
        'header_padding_top' => 'setHeaderPaddingTop',
        'header_text_decoration' => 'setHeaderTextDecoration',
        'table_background_color' => 'setTableBackgroundColor',
        'table_font_color' => 'setTableFontColor',
        'table_font_family' => 'setTableFontFamily',
        'table_font_size' => 'setTableFontSize',
        'table_text_align' => 'setTableTextAlign',
        'use_legacy_mobile_padding' => 'setUseLegacyMobilePadding'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'block_background_color' => 'getBlockBackgroundColor',
        'block_border_color' => 'getBlockBorderColor',
        'block_border_style' => 'getBlockBorderStyle',
        'block_border_width' => 'getBlockBorderWidth',
        'block_padding_bottom' => 'getBlockPaddingBottom',
        'block_padding_left' => 'getBlockPaddingLeft',
        'block_padding_right' => 'getBlockPaddingRight',
        'block_padding_top' => 'getBlockPaddingTop',
        'cell_horizontal_border_color' => 'getCellHorizontalBorderColor',
        'cell_horizontal_border_style' => 'getCellHorizontalBorderStyle',
        'cell_horizontal_border_width' => 'getCellHorizontalBorderWidth',
        'cell_padding_bottom' => 'getCellPaddingBottom',
        'cell_padding_left' => 'getCellPaddingLeft',
        'cell_padding_right' => 'getCellPaddingRight',
        'cell_padding_top' => 'getCellPaddingTop',
        'cell_vertical_align' => 'getCellVerticalAlign',
        'cell_vertical_border_color' => 'getCellVerticalBorderColor',
        'cell_vertical_border_style' => 'getCellVerticalBorderStyle',
        'cell_vertical_border_width' => 'getCellVerticalBorderWidth',
        'header_background_color' => 'getHeaderBackgroundColor',
        'header_font_color' => 'getHeaderFontColor',
        'header_font_family' => 'getHeaderFontFamily',
        'header_font_size' => 'getHeaderFontSize',
        'header_font_style' => 'getHeaderFontStyle',
        'header_font_weight' => 'getHeaderFontWeight',
        'header_letter_spacing' => 'getHeaderLetterSpacing',
        'header_line_height' => 'getHeaderLineHeight',
        'header_padding_bottom' => 'getHeaderPaddingBottom',
        'header_padding_left' => 'getHeaderPaddingLeft',
        'header_padding_right' => 'getHeaderPaddingRight',
        'header_padding_top' => 'getHeaderPaddingTop',
        'header_text_decoration' => 'getHeaderTextDecoration',
        'table_background_color' => 'getTableBackgroundColor',
        'table_font_color' => 'getTableFontColor',
        'table_font_family' => 'getTableFontFamily',
        'table_font_size' => 'getTableFontSize',
        'table_text_align' => 'getTableTextAlign',
        'use_legacy_mobile_padding' => 'getUseLegacyMobilePadding'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BLOCK_BORDER_STYLE_DASHED = 'dashed';
    public const BLOCK_BORDER_STYLE_DOTTED = 'dotted';
    public const BLOCK_BORDER_STYLE_GROOVE = 'groove';
    public const BLOCK_BORDER_STYLE_INSET = 'inset';
    public const BLOCK_BORDER_STYLE_NONE = 'none';
    public const BLOCK_BORDER_STYLE_OUTSET = 'outset';
    public const BLOCK_BORDER_STYLE_RIDGE = 'ridge';
    public const BLOCK_BORDER_STYLE_SOLID = 'solid';
    public const CELL_HORIZONTAL_BORDER_STYLE_DASHED = 'dashed';
    public const CELL_HORIZONTAL_BORDER_STYLE_DOTTED = 'dotted';
    public const CELL_HORIZONTAL_BORDER_STYLE_GROOVE = 'groove';
    public const CELL_HORIZONTAL_BORDER_STYLE_INSET = 'inset';
    public const CELL_HORIZONTAL_BORDER_STYLE_NONE = 'none';
    public const CELL_HORIZONTAL_BORDER_STYLE_OUTSET = 'outset';
    public const CELL_HORIZONTAL_BORDER_STYLE_RIDGE = 'ridge';
    public const CELL_HORIZONTAL_BORDER_STYLE_SOLID = 'solid';
    public const CELL_VERTICAL_ALIGN_BASELINE = 'baseline';
    public const CELL_VERTICAL_ALIGN_BOTTOM = 'bottom';
    public const CELL_VERTICAL_ALIGN_MIDDLE = 'middle';
    public const CELL_VERTICAL_ALIGN_TOP = 'top';
    public const CELL_VERTICAL_BORDER_STYLE_DASHED = 'dashed';
    public const CELL_VERTICAL_BORDER_STYLE_DOTTED = 'dotted';
    public const CELL_VERTICAL_BORDER_STYLE_GROOVE = 'groove';
    public const CELL_VERTICAL_BORDER_STYLE_INSET = 'inset';
    public const CELL_VERTICAL_BORDER_STYLE_NONE = 'none';
    public const CELL_VERTICAL_BORDER_STYLE_OUTSET = 'outset';
    public const CELL_VERTICAL_BORDER_STYLE_RIDGE = 'ridge';
    public const CELL_VERTICAL_BORDER_STYLE_SOLID = 'solid';
    public const HEADER_FONT_STYLE_ITALIC = 'italic';
    public const HEADER_FONT_STYLE_NORMAL = 'normal';
    public const TABLE_TEXT_ALIGN_CENTER = 'center';
    public const TABLE_TEXT_ALIGN_LEFT = 'left';
    public const TABLE_TEXT_ALIGN_RIGHT = 'right';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBlockBorderStyleAllowableValues()
    {
        return [
            self::BLOCK_BORDER_STYLE_DASHED,
            self::BLOCK_BORDER_STYLE_DOTTED,
            self::BLOCK_BORDER_STYLE_GROOVE,
            self::BLOCK_BORDER_STYLE_INSET,
            self::BLOCK_BORDER_STYLE_NONE,
            self::BLOCK_BORDER_STYLE_OUTSET,
            self::BLOCK_BORDER_STYLE_RIDGE,
            self::BLOCK_BORDER_STYLE_SOLID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCellHorizontalBorderStyleAllowableValues()
    {
        return [
            self::CELL_HORIZONTAL_BORDER_STYLE_DASHED,
            self::CELL_HORIZONTAL_BORDER_STYLE_DOTTED,
            self::CELL_HORIZONTAL_BORDER_STYLE_GROOVE,
            self::CELL_HORIZONTAL_BORDER_STYLE_INSET,
            self::CELL_HORIZONTAL_BORDER_STYLE_NONE,
            self::CELL_HORIZONTAL_BORDER_STYLE_OUTSET,
            self::CELL_HORIZONTAL_BORDER_STYLE_RIDGE,
            self::CELL_HORIZONTAL_BORDER_STYLE_SOLID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCellVerticalAlignAllowableValues()
    {
        return [
            self::CELL_VERTICAL_ALIGN_BASELINE,
            self::CELL_VERTICAL_ALIGN_BOTTOM,
            self::CELL_VERTICAL_ALIGN_MIDDLE,
            self::CELL_VERTICAL_ALIGN_TOP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCellVerticalBorderStyleAllowableValues()
    {
        return [
            self::CELL_VERTICAL_BORDER_STYLE_DASHED,
            self::CELL_VERTICAL_BORDER_STYLE_DOTTED,
            self::CELL_VERTICAL_BORDER_STYLE_GROOVE,
            self::CELL_VERTICAL_BORDER_STYLE_INSET,
            self::CELL_VERTICAL_BORDER_STYLE_NONE,
            self::CELL_VERTICAL_BORDER_STYLE_OUTSET,
            self::CELL_VERTICAL_BORDER_STYLE_RIDGE,
            self::CELL_VERTICAL_BORDER_STYLE_SOLID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getHeaderFontStyleAllowableValues()
    {
        return [
            self::HEADER_FONT_STYLE_ITALIC,
            self::HEADER_FONT_STYLE_NORMAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTableTextAlignAllowableValues()
    {
        return [
            self::TABLE_TEXT_ALIGN_CENTER,
            self::TABLE_TEXT_ALIGN_LEFT,
            self::TABLE_TEXT_ALIGN_RIGHT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('block_background_color', $data ?? [], null);
        $this->setIfExists('block_border_color', $data ?? [], null);
        $this->setIfExists('block_border_style', $data ?? [], null);
        $this->setIfExists('block_border_width', $data ?? [], null);
        $this->setIfExists('block_padding_bottom', $data ?? [], null);
        $this->setIfExists('block_padding_left', $data ?? [], null);
        $this->setIfExists('block_padding_right', $data ?? [], null);
        $this->setIfExists('block_padding_top', $data ?? [], null);
        $this->setIfExists('cell_horizontal_border_color', $data ?? [], null);
        $this->setIfExists('cell_horizontal_border_style', $data ?? [], null);
        $this->setIfExists('cell_horizontal_border_width', $data ?? [], null);
        $this->setIfExists('cell_padding_bottom', $data ?? [], null);
        $this->setIfExists('cell_padding_left', $data ?? [], null);
        $this->setIfExists('cell_padding_right', $data ?? [], null);
        $this->setIfExists('cell_padding_top', $data ?? [], null);
        $this->setIfExists('cell_vertical_align', $data ?? [], null);
        $this->setIfExists('cell_vertical_border_color', $data ?? [], null);
        $this->setIfExists('cell_vertical_border_style', $data ?? [], null);
        $this->setIfExists('cell_vertical_border_width', $data ?? [], null);
        $this->setIfExists('header_background_color', $data ?? [], null);
        $this->setIfExists('header_font_color', $data ?? [], null);
        $this->setIfExists('header_font_family', $data ?? [], null);
        $this->setIfExists('header_font_size', $data ?? [], null);
        $this->setIfExists('header_font_style', $data ?? [], null);
        $this->setIfExists('header_font_weight', $data ?? [], null);
        $this->setIfExists('header_letter_spacing', $data ?? [], null);
        $this->setIfExists('header_line_height', $data ?? [], null);
        $this->setIfExists('header_padding_bottom', $data ?? [], null);
        $this->setIfExists('header_padding_left', $data ?? [], null);
        $this->setIfExists('header_padding_right', $data ?? [], null);
        $this->setIfExists('header_padding_top', $data ?? [], null);
        $this->setIfExists('header_text_decoration', $data ?? [], null);
        $this->setIfExists('table_background_color', $data ?? [], null);
        $this->setIfExists('table_font_color', $data ?? [], null);
        $this->setIfExists('table_font_family', $data ?? [], null);
        $this->setIfExists('table_font_size', $data ?? [], null);
        $this->setIfExists('table_text_align', $data ?? [], null);
        $this->setIfExists('use_legacy_mobile_padding', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBlockBorderStyleAllowableValues();
        if (!is_null($this->container['block_border_style']) && !in_array($this->container['block_border_style'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'block_border_style', must be one of '%s'",
                $this->container['block_border_style'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCellHorizontalBorderStyleAllowableValues();
        if (!is_null($this->container['cell_horizontal_border_style']) && !in_array($this->container['cell_horizontal_border_style'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cell_horizontal_border_style', must be one of '%s'",
                $this->container['cell_horizontal_border_style'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCellVerticalAlignAllowableValues();
        if (!is_null($this->container['cell_vertical_align']) && !in_array($this->container['cell_vertical_align'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cell_vertical_align', must be one of '%s'",
                $this->container['cell_vertical_align'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCellVerticalBorderStyleAllowableValues();
        if (!is_null($this->container['cell_vertical_border_style']) && !in_array($this->container['cell_vertical_border_style'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'cell_vertical_border_style', must be one of '%s'",
                $this->container['cell_vertical_border_style'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getHeaderFontStyleAllowableValues();
        if (!is_null($this->container['header_font_style']) && !in_array($this->container['header_font_style'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'header_font_style', must be one of '%s'",
                $this->container['header_font_style'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTableTextAlignAllowableValues();
        if (!is_null($this->container['table_text_align']) && !in_array($this->container['table_text_align'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'table_text_align', must be one of '%s'",
                $this->container['table_text_align'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets block_background_color
     *
     * @return string|null
     */
    public function getBlockBackgroundColor()
    {
        return $this->container['block_background_color'];
    }

    /**
     * Sets block_background_color
     *
     * @param string|null $block_background_color block_background_color
     *
     * @return self
     */
    public function setBlockBackgroundColor($block_background_color)
    {
        if (is_null($block_background_color)) {
            array_push($this->openAPINullablesSetToNull, 'block_background_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_background_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_background_color'] = $block_background_color;

        return $this;
    }

    /**
     * Gets block_border_color
     *
     * @return string|null
     */
    public function getBlockBorderColor()
    {
        return $this->container['block_border_color'];
    }

    /**
     * Sets block_border_color
     *
     * @param string|null $block_border_color block_border_color
     *
     * @return self
     */
    public function setBlockBorderColor($block_border_color)
    {
        if (is_null($block_border_color)) {
            array_push($this->openAPINullablesSetToNull, 'block_border_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_border_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_border_color'] = $block_border_color;

        return $this;
    }

    /**
     * Gets block_border_style
     *
     * @return string|null
     */
    public function getBlockBorderStyle()
    {
        return $this->container['block_border_style'];
    }

    /**
     * Sets block_border_style
     *
     * @param string|null $block_border_style Border style.
     *
     * @return self
     */
    public function setBlockBorderStyle($block_border_style)
    {
        if (is_null($block_border_style)) {
            array_push($this->openAPINullablesSetToNull, 'block_border_style');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_border_style', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getBlockBorderStyleAllowableValues();
        if (!is_null($block_border_style) && !in_array($block_border_style, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'block_border_style', must be one of '%s'",
                    $block_border_style,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['block_border_style'] = $block_border_style;

        return $this;
    }

    /**
     * Gets block_border_width
     *
     * @return int|null
     */
    public function getBlockBorderWidth()
    {
        return $this->container['block_border_width'];
    }

    /**
     * Sets block_border_width
     *
     * @param int|null $block_border_width block_border_width
     *
     * @return self
     */
    public function setBlockBorderWidth($block_border_width)
    {
        if (is_null($block_border_width)) {
            array_push($this->openAPINullablesSetToNull, 'block_border_width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_border_width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_border_width'] = $block_border_width;

        return $this;
    }

    /**
     * Gets block_padding_bottom
     *
     * @return int|null
     */
    public function getBlockPaddingBottom()
    {
        return $this->container['block_padding_bottom'];
    }

    /**
     * Sets block_padding_bottom
     *
     * @param int|null $block_padding_bottom block_padding_bottom
     *
     * @return self
     */
    public function setBlockPaddingBottom($block_padding_bottom)
    {
        if (is_null($block_padding_bottom)) {
            array_push($this->openAPINullablesSetToNull, 'block_padding_bottom');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_padding_bottom', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_padding_bottom'] = $block_padding_bottom;

        return $this;
    }

    /**
     * Gets block_padding_left
     *
     * @return int|null
     */
    public function getBlockPaddingLeft()
    {
        return $this->container['block_padding_left'];
    }

    /**
     * Sets block_padding_left
     *
     * @param int|null $block_padding_left block_padding_left
     *
     * @return self
     */
    public function setBlockPaddingLeft($block_padding_left)
    {
        if (is_null($block_padding_left)) {
            array_push($this->openAPINullablesSetToNull, 'block_padding_left');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_padding_left', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_padding_left'] = $block_padding_left;

        return $this;
    }

    /**
     * Gets block_padding_right
     *
     * @return int|null
     */
    public function getBlockPaddingRight()
    {
        return $this->container['block_padding_right'];
    }

    /**
     * Sets block_padding_right
     *
     * @param int|null $block_padding_right block_padding_right
     *
     * @return self
     */
    public function setBlockPaddingRight($block_padding_right)
    {
        if (is_null($block_padding_right)) {
            array_push($this->openAPINullablesSetToNull, 'block_padding_right');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_padding_right', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_padding_right'] = $block_padding_right;

        return $this;
    }

    /**
     * Gets block_padding_top
     *
     * @return int|null
     */
    public function getBlockPaddingTop()
    {
        return $this->container['block_padding_top'];
    }

    /**
     * Sets block_padding_top
     *
     * @param int|null $block_padding_top block_padding_top
     *
     * @return self
     */
    public function setBlockPaddingTop($block_padding_top)
    {
        if (is_null($block_padding_top)) {
            array_push($this->openAPINullablesSetToNull, 'block_padding_top');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('block_padding_top', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['block_padding_top'] = $block_padding_top;

        return $this;
    }

    /**
     * Gets cell_horizontal_border_color
     *
     * @return string|null
     */
    public function getCellHorizontalBorderColor()
    {
        return $this->container['cell_horizontal_border_color'];
    }

    /**
     * Sets cell_horizontal_border_color
     *
     * @param string|null $cell_horizontal_border_color cell_horizontal_border_color
     *
     * @return self
     */
    public function setCellHorizontalBorderColor($cell_horizontal_border_color)
    {
        if (is_null($cell_horizontal_border_color)) {
            array_push($this->openAPINullablesSetToNull, 'cell_horizontal_border_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_horizontal_border_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_horizontal_border_color'] = $cell_horizontal_border_color;

        return $this;
    }

    /**
     * Gets cell_horizontal_border_style
     *
     * @return string|null
     */
    public function getCellHorizontalBorderStyle()
    {
        return $this->container['cell_horizontal_border_style'];
    }

    /**
     * Sets cell_horizontal_border_style
     *
     * @param string|null $cell_horizontal_border_style Border style.
     *
     * @return self
     */
    public function setCellHorizontalBorderStyle($cell_horizontal_border_style)
    {
        if (is_null($cell_horizontal_border_style)) {
            array_push($this->openAPINullablesSetToNull, 'cell_horizontal_border_style');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_horizontal_border_style', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getCellHorizontalBorderStyleAllowableValues();
        if (!is_null($cell_horizontal_border_style) && !in_array($cell_horizontal_border_style, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cell_horizontal_border_style', must be one of '%s'",
                    $cell_horizontal_border_style,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cell_horizontal_border_style'] = $cell_horizontal_border_style;

        return $this;
    }

    /**
     * Gets cell_horizontal_border_width
     *
     * @return int|null
     */
    public function getCellHorizontalBorderWidth()
    {
        return $this->container['cell_horizontal_border_width'];
    }

    /**
     * Sets cell_horizontal_border_width
     *
     * @param int|null $cell_horizontal_border_width cell_horizontal_border_width
     *
     * @return self
     */
    public function setCellHorizontalBorderWidth($cell_horizontal_border_width)
    {
        if (is_null($cell_horizontal_border_width)) {
            array_push($this->openAPINullablesSetToNull, 'cell_horizontal_border_width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_horizontal_border_width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_horizontal_border_width'] = $cell_horizontal_border_width;

        return $this;
    }

    /**
     * Gets cell_padding_bottom
     *
     * @return int|null
     */
    public function getCellPaddingBottom()
    {
        return $this->container['cell_padding_bottom'];
    }

    /**
     * Sets cell_padding_bottom
     *
     * @param int|null $cell_padding_bottom cell_padding_bottom
     *
     * @return self
     */
    public function setCellPaddingBottom($cell_padding_bottom)
    {
        if (is_null($cell_padding_bottom)) {
            array_push($this->openAPINullablesSetToNull, 'cell_padding_bottom');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_padding_bottom', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_padding_bottom'] = $cell_padding_bottom;

        return $this;
    }

    /**
     * Gets cell_padding_left
     *
     * @return int|null
     */
    public function getCellPaddingLeft()
    {
        return $this->container['cell_padding_left'];
    }

    /**
     * Sets cell_padding_left
     *
     * @param int|null $cell_padding_left cell_padding_left
     *
     * @return self
     */
    public function setCellPaddingLeft($cell_padding_left)
    {
        if (is_null($cell_padding_left)) {
            array_push($this->openAPINullablesSetToNull, 'cell_padding_left');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_padding_left', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_padding_left'] = $cell_padding_left;

        return $this;
    }

    /**
     * Gets cell_padding_right
     *
     * @return int|null
     */
    public function getCellPaddingRight()
    {
        return $this->container['cell_padding_right'];
    }

    /**
     * Sets cell_padding_right
     *
     * @param int|null $cell_padding_right cell_padding_right
     *
     * @return self
     */
    public function setCellPaddingRight($cell_padding_right)
    {
        if (is_null($cell_padding_right)) {
            array_push($this->openAPINullablesSetToNull, 'cell_padding_right');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_padding_right', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_padding_right'] = $cell_padding_right;

        return $this;
    }

    /**
     * Gets cell_padding_top
     *
     * @return int|null
     */
    public function getCellPaddingTop()
    {
        return $this->container['cell_padding_top'];
    }

    /**
     * Sets cell_padding_top
     *
     * @param int|null $cell_padding_top cell_padding_top
     *
     * @return self
     */
    public function setCellPaddingTop($cell_padding_top)
    {
        if (is_null($cell_padding_top)) {
            array_push($this->openAPINullablesSetToNull, 'cell_padding_top');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_padding_top', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_padding_top'] = $cell_padding_top;

        return $this;
    }

    /**
     * Gets cell_vertical_align
     *
     * @return string|null
     */
    public function getCellVerticalAlign()
    {
        return $this->container['cell_vertical_align'];
    }

    /**
     * Sets cell_vertical_align
     *
     * @param string|null $cell_vertical_align Vertical alignment.
     *
     * @return self
     */
    public function setCellVerticalAlign($cell_vertical_align)
    {
        if (is_null($cell_vertical_align)) {
            array_push($this->openAPINullablesSetToNull, 'cell_vertical_align');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_vertical_align', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getCellVerticalAlignAllowableValues();
        if (!is_null($cell_vertical_align) && !in_array($cell_vertical_align, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cell_vertical_align', must be one of '%s'",
                    $cell_vertical_align,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cell_vertical_align'] = $cell_vertical_align;

        return $this;
    }

    /**
     * Gets cell_vertical_border_color
     *
     * @return string|null
     */
    public function getCellVerticalBorderColor()
    {
        return $this->container['cell_vertical_border_color'];
    }

    /**
     * Sets cell_vertical_border_color
     *
     * @param string|null $cell_vertical_border_color cell_vertical_border_color
     *
     * @return self
     */
    public function setCellVerticalBorderColor($cell_vertical_border_color)
    {
        if (is_null($cell_vertical_border_color)) {
            array_push($this->openAPINullablesSetToNull, 'cell_vertical_border_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_vertical_border_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_vertical_border_color'] = $cell_vertical_border_color;

        return $this;
    }

    /**
     * Gets cell_vertical_border_style
     *
     * @return string|null
     */
    public function getCellVerticalBorderStyle()
    {
        return $this->container['cell_vertical_border_style'];
    }

    /**
     * Sets cell_vertical_border_style
     *
     * @param string|null $cell_vertical_border_style Border style.
     *
     * @return self
     */
    public function setCellVerticalBorderStyle($cell_vertical_border_style)
    {
        if (is_null($cell_vertical_border_style)) {
            array_push($this->openAPINullablesSetToNull, 'cell_vertical_border_style');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_vertical_border_style', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getCellVerticalBorderStyleAllowableValues();
        if (!is_null($cell_vertical_border_style) && !in_array($cell_vertical_border_style, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'cell_vertical_border_style', must be one of '%s'",
                    $cell_vertical_border_style,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cell_vertical_border_style'] = $cell_vertical_border_style;

        return $this;
    }

    /**
     * Gets cell_vertical_border_width
     *
     * @return int|null
     */
    public function getCellVerticalBorderWidth()
    {
        return $this->container['cell_vertical_border_width'];
    }

    /**
     * Sets cell_vertical_border_width
     *
     * @param int|null $cell_vertical_border_width cell_vertical_border_width
     *
     * @return self
     */
    public function setCellVerticalBorderWidth($cell_vertical_border_width)
    {
        if (is_null($cell_vertical_border_width)) {
            array_push($this->openAPINullablesSetToNull, 'cell_vertical_border_width');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cell_vertical_border_width', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cell_vertical_border_width'] = $cell_vertical_border_width;

        return $this;
    }

    /**
     * Gets header_background_color
     *
     * @return string|null
     */
    public function getHeaderBackgroundColor()
    {
        return $this->container['header_background_color'];
    }

    /**
     * Sets header_background_color
     *
     * @param string|null $header_background_color header_background_color
     *
     * @return self
     */
    public function setHeaderBackgroundColor($header_background_color)
    {
        if (is_null($header_background_color)) {
            array_push($this->openAPINullablesSetToNull, 'header_background_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_background_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_background_color'] = $header_background_color;

        return $this;
    }

    /**
     * Gets header_font_color
     *
     * @return string|null
     */
    public function getHeaderFontColor()
    {
        return $this->container['header_font_color'];
    }

    /**
     * Sets header_font_color
     *
     * @param string|null $header_font_color header_font_color
     *
     * @return self
     */
    public function setHeaderFontColor($header_font_color)
    {
        if (is_null($header_font_color)) {
            array_push($this->openAPINullablesSetToNull, 'header_font_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_font_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_font_color'] = $header_font_color;

        return $this;
    }

    /**
     * Gets header_font_family
     *
     * @return string|null
     */
    public function getHeaderFontFamily()
    {
        return $this->container['header_font_family'];
    }

    /**
     * Sets header_font_family
     *
     * @param string|null $header_font_family header_font_family
     *
     * @return self
     */
    public function setHeaderFontFamily($header_font_family)
    {
        if (is_null($header_font_family)) {
            array_push($this->openAPINullablesSetToNull, 'header_font_family');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_font_family', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_font_family'] = $header_font_family;

        return $this;
    }

    /**
     * Gets header_font_size
     *
     * @return int|null
     */
    public function getHeaderFontSize()
    {
        return $this->container['header_font_size'];
    }

    /**
     * Sets header_font_size
     *
     * @param int|null $header_font_size header_font_size
     *
     * @return self
     */
    public function setHeaderFontSize($header_font_size)
    {
        if (is_null($header_font_size)) {
            array_push($this->openAPINullablesSetToNull, 'header_font_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_font_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_font_size'] = $header_font_size;

        return $this;
    }

    /**
     * Gets header_font_style
     *
     * @return string|null
     */
    public function getHeaderFontStyle()
    {
        return $this->container['header_font_style'];
    }

    /**
     * Sets header_font_style
     *
     * @param string|null $header_font_style Font style.
     *
     * @return self
     */
    public function setHeaderFontStyle($header_font_style)
    {
        if (is_null($header_font_style)) {
            array_push($this->openAPINullablesSetToNull, 'header_font_style');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_font_style', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getHeaderFontStyleAllowableValues();
        if (!is_null($header_font_style) && !in_array($header_font_style, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'header_font_style', must be one of '%s'",
                    $header_font_style,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['header_font_style'] = $header_font_style;

        return $this;
    }

    /**
     * Gets header_font_weight
     *
     * @return string|null
     */
    public function getHeaderFontWeight()
    {
        return $this->container['header_font_weight'];
    }

    /**
     * Sets header_font_weight
     *
     * @param string|null $header_font_weight header_font_weight
     *
     * @return self
     */
    public function setHeaderFontWeight($header_font_weight)
    {
        if (is_null($header_font_weight)) {
            array_push($this->openAPINullablesSetToNull, 'header_font_weight');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_font_weight', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_font_weight'] = $header_font_weight;

        return $this;
    }

    /**
     * Gets header_letter_spacing
     *
     * @return int|null
     */
    public function getHeaderLetterSpacing()
    {
        return $this->container['header_letter_spacing'];
    }

    /**
     * Sets header_letter_spacing
     *
     * @param int|null $header_letter_spacing header_letter_spacing
     *
     * @return self
     */
    public function setHeaderLetterSpacing($header_letter_spacing)
    {
        if (is_null($header_letter_spacing)) {
            array_push($this->openAPINullablesSetToNull, 'header_letter_spacing');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_letter_spacing', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_letter_spacing'] = $header_letter_spacing;

        return $this;
    }

    /**
     * Gets header_line_height
     *
     * @return float|null
     */
    public function getHeaderLineHeight()
    {
        return $this->container['header_line_height'];
    }

    /**
     * Sets header_line_height
     *
     * @param float|null $header_line_height header_line_height
     *
     * @return self
     */
    public function setHeaderLineHeight($header_line_height)
    {
        if (is_null($header_line_height)) {
            array_push($this->openAPINullablesSetToNull, 'header_line_height');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_line_height', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_line_height'] = $header_line_height;

        return $this;
    }

    /**
     * Gets header_padding_bottom
     *
     * @return int|null
     */
    public function getHeaderPaddingBottom()
    {
        return $this->container['header_padding_bottom'];
    }

    /**
     * Sets header_padding_bottom
     *
     * @param int|null $header_padding_bottom header_padding_bottom
     *
     * @return self
     */
    public function setHeaderPaddingBottom($header_padding_bottom)
    {
        if (is_null($header_padding_bottom)) {
            array_push($this->openAPINullablesSetToNull, 'header_padding_bottom');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_padding_bottom', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_padding_bottom'] = $header_padding_bottom;

        return $this;
    }

    /**
     * Gets header_padding_left
     *
     * @return int|null
     */
    public function getHeaderPaddingLeft()
    {
        return $this->container['header_padding_left'];
    }

    /**
     * Sets header_padding_left
     *
     * @param int|null $header_padding_left header_padding_left
     *
     * @return self
     */
    public function setHeaderPaddingLeft($header_padding_left)
    {
        if (is_null($header_padding_left)) {
            array_push($this->openAPINullablesSetToNull, 'header_padding_left');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_padding_left', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_padding_left'] = $header_padding_left;

        return $this;
    }

    /**
     * Gets header_padding_right
     *
     * @return int|null
     */
    public function getHeaderPaddingRight()
    {
        return $this->container['header_padding_right'];
    }

    /**
     * Sets header_padding_right
     *
     * @param int|null $header_padding_right header_padding_right
     *
     * @return self
     */
    public function setHeaderPaddingRight($header_padding_right)
    {
        if (is_null($header_padding_right)) {
            array_push($this->openAPINullablesSetToNull, 'header_padding_right');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_padding_right', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_padding_right'] = $header_padding_right;

        return $this;
    }

    /**
     * Gets header_padding_top
     *
     * @return int|null
     */
    public function getHeaderPaddingTop()
    {
        return $this->container['header_padding_top'];
    }

    /**
     * Sets header_padding_top
     *
     * @param int|null $header_padding_top header_padding_top
     *
     * @return self
     */
    public function setHeaderPaddingTop($header_padding_top)
    {
        if (is_null($header_padding_top)) {
            array_push($this->openAPINullablesSetToNull, 'header_padding_top');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_padding_top', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_padding_top'] = $header_padding_top;

        return $this;
    }

    /**
     * Gets header_text_decoration
     *
     * @return string|null
     */
    public function getHeaderTextDecoration()
    {
        return $this->container['header_text_decoration'];
    }

    /**
     * Sets header_text_decoration
     *
     * @param string|null $header_text_decoration header_text_decoration
     *
     * @return self
     */
    public function setHeaderTextDecoration($header_text_decoration)
    {
        if (is_null($header_text_decoration)) {
            array_push($this->openAPINullablesSetToNull, 'header_text_decoration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('header_text_decoration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['header_text_decoration'] = $header_text_decoration;

        return $this;
    }

    /**
     * Gets table_background_color
     *
     * @return string|null
     */
    public function getTableBackgroundColor()
    {
        return $this->container['table_background_color'];
    }

    /**
     * Sets table_background_color
     *
     * @param string|null $table_background_color table_background_color
     *
     * @return self
     */
    public function setTableBackgroundColor($table_background_color)
    {
        if (is_null($table_background_color)) {
            array_push($this->openAPINullablesSetToNull, 'table_background_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('table_background_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['table_background_color'] = $table_background_color;

        return $this;
    }

    /**
     * Gets table_font_color
     *
     * @return string|null
     */
    public function getTableFontColor()
    {
        return $this->container['table_font_color'];
    }

    /**
     * Sets table_font_color
     *
     * @param string|null $table_font_color table_font_color
     *
     * @return self
     */
    public function setTableFontColor($table_font_color)
    {
        if (is_null($table_font_color)) {
            array_push($this->openAPINullablesSetToNull, 'table_font_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('table_font_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['table_font_color'] = $table_font_color;

        return $this;
    }

    /**
     * Gets table_font_family
     *
     * @return string|null
     */
    public function getTableFontFamily()
    {
        return $this->container['table_font_family'];
    }

    /**
     * Sets table_font_family
     *
     * @param string|null $table_font_family table_font_family
     *
     * @return self
     */
    public function setTableFontFamily($table_font_family)
    {
        if (is_null($table_font_family)) {
            array_push($this->openAPINullablesSetToNull, 'table_font_family');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('table_font_family', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['table_font_family'] = $table_font_family;

        return $this;
    }

    /**
     * Gets table_font_size
     *
     * @return int|null
     */
    public function getTableFontSize()
    {
        return $this->container['table_font_size'];
    }

    /**
     * Sets table_font_size
     *
     * @param int|null $table_font_size table_font_size
     *
     * @return self
     */
    public function setTableFontSize($table_font_size)
    {
        if (is_null($table_font_size)) {
            array_push($this->openAPINullablesSetToNull, 'table_font_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('table_font_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['table_font_size'] = $table_font_size;

        return $this;
    }

    /**
     * Gets table_text_align
     *
     * @return string|null
     */
    public function getTableTextAlign()
    {
        return $this->container['table_text_align'];
    }

    /**
     * Sets table_text_align
     *
     * @param string|null $table_text_align Text Alignment.
     *
     * @return self
     */
    public function setTableTextAlign($table_text_align)
    {
        if (is_null($table_text_align)) {
            array_push($this->openAPINullablesSetToNull, 'table_text_align');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('table_text_align', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getTableTextAlignAllowableValues();
        if (!is_null($table_text_align) && !in_array($table_text_align, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'table_text_align', must be one of '%s'",
                    $table_text_align,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['table_text_align'] = $table_text_align;

        return $this;
    }

    /**
     * Gets use_legacy_mobile_padding
     *
     * @return bool|null
     */
    public function getUseLegacyMobilePadding()
    {
        return $this->container['use_legacy_mobile_padding'];
    }

    /**
     * Sets use_legacy_mobile_padding
     *
     * @param bool|null $use_legacy_mobile_padding use_legacy_mobile_padding
     *
     * @return self
     */
    public function setUseLegacyMobilePadding($use_legacy_mobile_padding)
    {
        if (is_null($use_legacy_mobile_padding)) {
            array_push($this->openAPINullablesSetToNull, 'use_legacy_mobile_padding');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('use_legacy_mobile_padding', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['use_legacy_mobile_padding'] = $use_legacy_mobile_padding;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


